name: Format

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: DoozyX/clang-format-lint-action@v0.8
      name: check
      with:
        source: '.'
        extensions: 'cpp,hpp'
        style: file
        clangFormatVersion: 10
