name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 1 * *"

env:
  DOCKER_BUILDKIT: 1
  OMP_NUM_THREADS: 1

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [cpu_ifirst, cpu_kfirst, cuda, hip]
        runtime: [single_node, simple_mpi, gcl, ghex_comm]
        exclude:
          - backend: hip
            runtime: ghex_comm
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - name: build
      run: >
        docker build
        --cache-from fthaler/gtbench:${{ matrix.backend }}-${{ matrix.runtime }}
        --progress=plain
        --build-arg BUILD_FROM=$(
        if [ ${{ matrix.backend }} = cuda ]; then echo nvidia/cuda:11.0-devel-ubuntu18.04;
        elif [ ${{ matrix.backend }} = hip ]; then echo rocm/dev-ubuntu-18.04;
        else echo ubuntu:20.04;
        fi)
        --build-arg GTBENCH_BACKEND=$(
        if [ ${{ matrix.backend }} = cuda ] || [ ${{ matrix.backend }} = hip ]; then echo gpu; else echo ${{ matrix.backend }};
        fi)
        --build-arg GTBENCH_RUNTIME=${{ matrix.runtime }}
        --build-arg BUILDKIT_INLINE_CACHE=1
        -t fthaler/gtbench:${{ matrix.backend }}-${{ matrix.runtime }}
        .
    - name: test
      if: ${{ matrix.backend != 'cuda' && matrix.backend != 'hip' }}
      run: >
        docker run --rm fthaler/gtbench:${{ matrix.backend }}-${{ matrix.runtime }} benchmark --domain-size 11 13 17 --runs 1 &&
        docker run --rm fthaler/gtbench:${{ matrix.backend }}-${{ matrix.runtime }} convergence_tests
    - name: push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gtbench' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u fthaler --password-stdin &&
        docker push fthaler/gtbench:${{ matrix.backend }}-${{ matrix.runtime }} &&
        docker logout

