name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [cpu_ifirst, cpu_kfirst, gpu]
        runtime: [single_node, simple_mpi, gcl, ghex_comm]
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - name: build
      run: >
        docker build
        --build-arg BUILD_FROM=$(if [ ${{ matrix.backend }} = gpu ]; then echo nvidia/cuda:11.0-devel-ubuntu18.04; else echo ubuntu:20.04; fi)
        --build-arg GTBENCH_BACKEND=${{ matrix.backend }}
        --build-arg GTBENCH_RUNTIME=${{ matrix.runtime }}
        -t fthaler/gtbench:${{ matrix.backend }}_${{ matrix.runtime }}
        .
    - name: test
      if: ${{ matrix.backend != 'gpu' }}
      run: >
        docker run --rm fthaler/gtbench:${{ matrix.backend }}_${{ matrix.runtime }} /usr/bin/benchmark --domain-size 10 10 &&
        docker run --rm fthaler/gtbench:${{ matrix.backend }}_${{ matrix.runtime }} /usr/bin/convergence_tests
    - name: push
      if: ${{ github.event_name == 'push' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u fthaler --password-stdin &&
        docker push fthaler/gtbench &&
        docker logout
        
